USE apollo_booking;

INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (1, 'Northeastern Dance Club', 'Student-run dance organization featuring multiple styles including hip-hop, contemporary, and K-pop', 'nudanceclub@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (2, 'Club Squash', 'Competitive and recreational squash team for all skill levels', 'clubsquash@northeastern.edu', 1);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (3, 'AI Club', 'Explores artificial intelligence topics through workshops, projects, and speaker events', 'aiclub@northeastern.edu', 1);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (4, 'Husky Ambassadors', 'Student tour guides and campus event volunteers', 'huskyambassadors@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (5, 'NU Entrepreneurs', 'Startup incubator and networking community for student founders', 'nuentrepreneurs@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (6, 'Women in Tech', 'Supports women and non-binary students in technology fields', 'womenintech@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (7, 'Photography Club', 'Community for photography enthusiasts to share work and go on photo walks', 'photoclub@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (8, 'Model United Nations', 'Prepares students for MUN conferences through debate and research', 'numun@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (9, 'Club Soccer', 'Competitive co-ed soccer club competing in regional leagues', 'clubsoccer@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (10, 'Northeastern Consulting Group', 'Pro-bono consulting for local nonprofits and startups', 'nuconsulting@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (11, 'Outing Club', 'Organizes hiking, camping, skiing, and other outdoor adventures', 'outingclub@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (12, 'NU Tabletop', 'Board game and tabletop RPG community', 'nutabletop@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (13, 'Data Science Club', 'Workshops and projects focused on data analytics and machine learning', 'datasci@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (14, 'Pre-Med Society', 'Resources and community for pre-medical students', 'premed@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (15, 'NU Debate', 'Competitive debate team participating in national tournaments', 'nudebate@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (16, 'Robotics Club', 'Builds and programs robots for competitions and demos', 'nurobotics@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (17, 'Finance Club', 'Investment education, stock pitch competitions, and career prep', 'financeclub@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (18, 'NU Improv', 'Comedy improv performances and workshops', 'nuimprov@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (19, 'Badminton Club', 'Recreational and competitive badminton for all levels', 'badminton@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (20, 'Environmental Action', 'Sustainability initiatives and environmental advocacy on campus', 'envaction@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (21, 'Korean Student Association', 'Celebrates Korean culture through events, food, and performances', 'ksa@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (22, 'Club Running', 'Group runs and training for races from 5Ks to marathons', 'clubrunning@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (23, 'Cyber Security Club', 'Capture-the-flag competitions and security workshops', 'cybersec@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (24, 'NU Shakespeare', 'Student-produced Shakespeare plays and theatrical performances', 'nushakespeare@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (25, 'Club Volleyball', 'Co-ed competitive volleyball club', 'clubvolleyball@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (26, 'Blockchain at NEU', 'Education and projects around blockchain and Web3 technologies', 'blockchain@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (27, 'Chinese Student Association', 'Cultural events and community for Chinese and Chinese-American students', 'csa@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (28, 'NU Acapella', 'Student acapella group performing covers and originals', 'nuacapella@northeastern.edu', 1);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (29, 'Chess Club', 'Casual and competitive chess play with weekly meetups', 'chessclub@northeastern.edu', 0);
INSERT INTO clubs (club_id, club_name, description, email, suspended) VALUES (30, 'Club Lacrosse', 'Competitive club lacrosse team', 'clublax@northeastern.edu', 1);