INSERT INTO events (event_id, event_name, event_type, description, booking_id) VALUES
(1, 'Spring Charity Bake Sale',      'fundraiser', 'Annual bake sale to raise funds for club programming and community outreach initiatives.',          1),
(2, 'Cultural Dance Showcase',        'showcase',   'A student-led performance highlighting traditional and contemporary dance styles from around the world.', 2),
(3, 'Annual Alumni Mixer',            'social',     'Networking event connecting current club members with alumni working in relevant industries.',          5),
(4, 'Tech Talk: AI in Everyday Life', 'seminar',    'Panel discussion featuring guest speakers on the impact of artificial intelligence in modern society.',  11),
(5,  'Spring Blood Drive',              'fundraiser',   'Campus blood drive organized in partnership with the Red Cross to support local hospital reserves.',          13),
(6,  'Nonprofit Strategy Workshop',    'workshop',     'Hands-on session where NCG members develop consulting deliverables for a local nonprofit client.',           46),
(7,  'Spring Hiking Trip Kickoff',     'meeting',      'Planning meeting to finalize routes, gear lists, and carpools for the Outing Club spring trip.',             47),
(8,  'Dungeons & Dragons Night',       'social',       'Open campaign night welcoming new and returning players to the club tabletop RPG sessions.',                 48),
(9,  'Spring Comedy Showcase',         'showcase',     'End-of-semester improv performance open to the campus community featuring original sketches.',               49),
(10, 'Interclub Badminton Tournament', 'competition',  'Round-robin tournament pitting Northeastern badminton players against visiting club teams.',                  50),
(11, 'Campus Sustainability Fair',     'fundraiser',   'Tabling event raising awareness and funds for local environmental initiatives through games and raffles.',    51),
(12, 'Morning 5K Fun Run',             'social',       'Casual group run around the Fenway loop open to all fitness levels, followed by a club meetup.',             52),
(13, 'Capture the Flag Practice',      'competition',  'Internal CTF warm-up round to prepare members for the upcoming regional cybersecurity competition.',         53),
(14, 'Romeo & Juliet Rehearsal',       'rehearsal',    'Full-cast rehearsal for the spring production of Romeo & Juliet, focusing on Acts III through V.',           54),
(15, 'Web3 Developer Meetup',          'seminar',      'Lightning talks and networking session on decentralized applications and smart contract development.',        55),
(16, 'K-Pop Dance Workshop',           'workshop',     'Choreography workshop teaching a K-pop routine, open to all experience levels.',                             56),
(17, 'New Member Orientation',         'orientation',  'Welcome session for incoming Husky Ambassadors covering tour routes, policies, and event volunteering.',     57),
(18, 'Startup Pitch Night',            'showcase',     'Student founders pitch their ventures to a panel of alumni entrepreneurs and local investors.',              58),
(19, 'Tech Industry Panel',            'seminar',      'Panel of women professionals in tech sharing career advice, industry trends, and internship guidance.',      59),
(20, 'MUN Conference Prep Session',    'workshop',     'Delegate research and position paper workshop in advance of the regional Model UN spring conference.',       60),
(21, 'Client Case Presentation',       'meeting',      'NCG team presents final consulting recommendations to a nonprofit client board of directors.',               61),
(22, 'Rock Climbing Social Night',     'social',       'Casual indoor climbing session at the campus facility, welcoming climbers of all skill levels.',             62),
(23, 'MCAT Prep Study Session',        'workshop',     'Structured group study covering biology and chemistry sections with practice questions and review.',         63),
(24, 'Stock Pitch Competition',        'competition',  'Members pitch equity investments to a mock portfolio committee, judged on research depth and presentation.',  64),
(25, 'Improv Jam Session',             'social',       'Low-stakes open improv practice night for members to workshop new games and warm-up exercises.',             65),
(26, 'Earth Week Cleanup Drive',       'fundraiser',   'Campus and neighborhood cleanup in honor of Earth Week, with donation matching from a local sponsor.',       66),
(27, 'Lunar New Year Celebration',     'social',       'Cultural celebration featuring traditional food, performances, and activities honoring the Lunar New Year.', 67),
(28, 'Board Game Tournament',          'competition',  'Scheduled single-elimination board game bracket across multiple titles — cancelled due to low registration.', 68),
(29, 'Chess Open Tournament',          'competition',  'Open-format chess tournament planned for all skill levels — cancelled due to venue scheduling conflict.',     71),
(30, 'Midsummer Night Rehearsal',      'rehearsal',    'Scheduled full-cast rehearsal for A Midsummer Night\'s Dream — booking was a no-show.',                     74);
